server:
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: 654321
      initial-size: 1
      max-active: 20
      min-idle: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: tk.sample.tkdemo.base.MyMapper
  not-empty: false
  identity: MYSQL
